  name: CI
  on:
    pull_request:
      branches:
        - develop
        - master
        - qa
        - uat
  jobs:
    gitlint:
      runs-on: ubuntu-latest
      name: GitLint
      steps:
        - name: Lint commits, branches, and pull requests
          uses: aschbacd/gitlint-action@v1.1.1
          with:
            re-branch-name: /(develop|master|qa|uat|(feature|bugfix|integration|rnd)/\w/i)
    flutter_analyze:
      runs-on: ubuntu-latest
      name: Run flutter analyze
      needs: [gitlint]
      steps:
        - uses: actions/checkout@v4
        - uses: subosito/flutter-action@v2
          with:
            flutter-version: '3.16.9'
            channel: 'stable'
        - run: flutter --version
        - run: flutter pub get
        - run: flutter analyze
    flutter_test:
      runs-on: ubuntu-latest
      name: Run flutter test
      needs: [flutter_analyze]
      steps:
        - uses: actions/checkout@v4
        - uses: subosito/flutter-action@v2
          with:
            flutter-version: '3.16.9'
            channel: 'stable'
        - run: flutter pub get
        - run: flutter test
    flutter_build_appbundle:
      runs-on: ubuntu-latest
      name: Build flutter (Android)
      needs: [flutter_test]
      steps:
        - uses: actions/checkout@v4
        - uses: subosito/flutter-action@v2
          with:
            flutter-version: '3.16.9'
            channel: 'stable'
        - run: flutter pub get
        - run: flutter clean
        - run: flutter build appbundle
